schema: "classroom50/repo-config/v1"
classroom: "cse2506-fall2026"
assignment: "studio-ift"
owner:
  username: "cngamvir"
  id: 179256081
  accepted_at: "2026-09-02T03:22:18Z"
source:
  owner: "ckelleher-wustl"
  owner_id: 75854859
  repo: "f22_IF_template"
  branch: "master"
